# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Thinking Fixed"
description: > # this means to ignore newlines until "email:"
    The business of bicycles in China. A story of following a passion, starting from scratch, making decisions and getting things done.

email: drew@wearefactoryfive.com
#blog logo
logo: "/assets/images/lattice-chainring.jpg"
# blog cover
cover: "/assets/images/bikes-header.jpg"

name: 'Drew Bates'
author: 'Drew Bates'
author_image: "/assets/images/lattice-chainring.jpg"

paginate:	7

url: "http://192.184.88.213" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/triplefivedrew
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/triplefivedrew
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	google-plus
    url:	https://plus.google.com/105147159312725781529/posts
    desc:	Add me on google+
    share_url:
    share_title:
    share_link:
